#1=((name . "number nine")
    (owner . #2="dev@deoxybyte.co.uk")
    (definition-done "Public interface documented." "Committed into a VCS." "All acceptance criteria met.")
    (stories
     ((product . #1#)
      (owner . #2#)
      (role . "developer")
      (goal . "to be able to add stories in the product backlog to a sprint backlog")
      (benefit . "I can start a sprint")
      (criteria)
      (cost . 0)
      (created 20874 52923 979418 0)
      (number . 3)
      (priority . 0))
     ((product . #1#)
      (owner . #2#)
      (role . "developer")
      (goal . "to be able to add stories to the product backlog")
      (benefit . "I can assign work to be done")
      (criteria)
      (cost . 0)
      (created 20874 52879 727819 0)
      (number . 2)
      (priority . 0))
     ((product . #1#)
      (owner . #2#)
      (role . "developer")
      (goal . "to be able to mark stories as todo, in progress or done")
      (benefit . "I can measure progress")
      (criteria)
      (cost . 0)
      (created 20874 52797 845314 0)
      (number . 1)
      (priority . 0)))
    (backlog)
    (sprints)
    (story-counter . 3)
    (sprint-counter . 0))
